// This file is generated by Claude. Do not edit this file directly. Instead, edit the source code and regenerate this file.
// Other options if you want to edit this file copy it and paste the source code to Claude to modify it, then copy the modified code back here.


"use client";

export function RobotAvatar({ className }: { className?: string }) {
    return (
        <>
            <style>{`
                @keyframes robot-float {
                    0%, 100% { transform: translateY(0px); }
                    50% { transform: translateY(-8px); }
                }

                @keyframes robot-blink {
                    0%, 90%, 100% { transform: scaleY(1); }
                    95% { transform: scaleY(0.08); }
                }

                @keyframes robot-antenna-sway {
                    0%, 100% { transform: rotate(0deg); }
                    25% { transform: rotate(6deg); }
                    75% { transform: rotate(-6deg); }
                }

                @keyframes robot-mouth-breathe {
                    0%, 100% { transform: scaleX(1); }
                    50% { transform: scaleX(0.85); }
                }

                @keyframes robot-shine {
                    0%, 100% { opacity: 0.6; }
                    50% { opacity: 1; }
                }

                .robot-whole {
                    animation: robot-float 3.6s ease-in-out infinite;
                }

                .robot-eye-left {
                    transform-origin: 65.66px 81.73px;
                    animation: robot-blink 4s ease-in-out infinite;
                }

                .robot-eye-right {
                    transform-origin: 95.54px 81.73px;
                    animation: robot-blink 4s ease-in-out infinite 0.05s;
                }

                .robot-antenna {
                    transform-origin: 80.5px 30px;
                    animation: robot-antenna-sway 2.8s ease-in-out infinite;
                }

                .robot-mouth {
                    transform-origin: 81.85px 110.46px;
                    animation: robot-mouth-breathe 3.6s ease-in-out infinite;
                }

                .robot-shine {
                    animation: robot-shine 3.6s ease-in-out infinite;
                }
            `}</style>

            {/*
                viewBox is expanded with padding on all sides (-30 -20 220 240)
                so the glow filter has room to bleed outward without clipping.
                The SVG canvas itself is wider/taller than the art to absorb the blur.
            */}
            <svg
                width="220"
                height="260"
                viewBox="-30 -20 220 240"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                className={className}
            >
                <defs>
                    {/*
                        feMerge approach: render a cyan-tinted blurred copy BEHIND
                        the original — no dark alpha fringe, pure additive glow.
                        x/y/width/height are large so blur never clips.
                    */}
                    <filter id="glow-all" x="-25%" y="-25%" width="150%" height="150%" colorInterpolationFilters="sRGB">
                        <feGaussianBlur in="SourceGraphic" stdDeviation="3" result="blur"/>
                        <feColorMatrix in="blur" type="matrix" values="0 0 0 0 0 0 0 0 0 0.831 0 0 0 0 1 0 0 0 0.7 0" result="coloredBlur"/>
                        <feMerge>
                            <feMergeNode in="coloredBlur"/>
                            <feMergeNode in="SourceGraphic"/>
                        </feMerge>
                    </filter>

                    <linearGradient id="g0" x1="80.2754" y1="146.817" x2="80.2754" y2="182.364" gradientUnits="userSpaceOnUse">
                        <stop stopColor="#00D4FF"/>
                        <stop offset="1" stopColor="#0FABCA"/>
                    </linearGradient>
                    <linearGradient id="g1" x1="50.4423" y1="144.908" x2="50.4423" y2="164.329" gradientUnits="userSpaceOnUse">
                        <stop stopColor="#00D4FF"/>
                        <stop offset="1" stopColor="#0FABCA"/>
                    </linearGradient>
                    <linearGradient id="g2" x1="114.479" y1="146.74" x2="114.479" y2="166.161" gradientUnits="userSpaceOnUse">
                        <stop stopColor="#00D4FF"/>
                        <stop offset="1" stopColor="#0FABCA"/>
                    </linearGradient>
                    <linearGradient id="g3" x1="81.2405" y1="48.1562" x2="81.2405" y2="146.041" gradientUnits="userSpaceOnUse">
                        <stop stopColor="#00D4FF"/>
                        <stop offset="1" stopColor="#0FABCA"/>
                    </linearGradient>
                    <linearGradient id="g4" x1="80.5145" y1="15.7405" x2="80.5145" y2="43.7732" gradientUnits="userSpaceOnUse">
                        <stop stopColor="#00D4FF"/>
                        <stop offset="1" stopColor="#0FABCA"/>
                    </linearGradient>
                </defs>

                {/* Single group: everything floats + glows together */}
                <g className="robot-whole" filter="url(#glow-all)">

                    {/* ── Feet ── */}
                    <path d="M100.72 167.712C101.304 180.374 87.409 182.728 80.023 182.322C63.2219 181.399 59.813 173.038 59.813 167.712C60.7869 154.776 77.8316 145.311 84.4059 147.015C85.6234 147.331 100.136 155.05 100.72 167.712Z" fill="url(#g0)"/>
                    <path d="M40.3333 151.885C48.7095 144.678 58.3518 144.093 62.2477 145.554C64.6451 146.453 63.8731 150.181 63.7087 150.911C61.5173 160.651 53.1196 163.63 45.9336 164.303C41.0639 164.759 31.9571 159.092 40.3333 151.885Z" fill="url(#g1)"/>
                    <path d="M124.588 153.717C116.212 146.51 106.569 145.925 102.673 147.386C100.276 148.285 101.048 152.013 101.212 152.743C103.404 162.483 111.802 165.463 118.988 166.136C123.857 166.591 132.964 160.925 124.588 153.717Z" fill="url(#g2)"/>
                    <circle cx="79.7795" cy="166.464" r="6.57435" fill="white"/>
                    <path
                        className="robot-shine"
                        d="M88.6462 159.058C88.456 158.867 88.1476 158.867 87.9575 159.058C87.7673 159.248 87.7673 159.556 87.9575 159.746L88.3018 159.402L88.6462 159.058ZM88.3018 159.402L87.9575 159.746C88.6432 160.432 89.5867 161.711 90.144 163.278C90.6988 164.839 90.8606 166.652 90.0492 168.455L90.4933 168.655L90.9374 168.855C91.8791 166.762 91.6756 164.679 91.0617 162.952C90.4502 161.232 89.4214 159.833 88.6462 159.058L88.3018 159.402Z"
                        fill="white"
                    />

                    {/* ── Body ── */}
                    <ellipse cx="81.2405" cy="97.0986" rx="65.5" ry="48.9424" fill="url(#g3)"/>

                    {/* ── Eyes ── */}
                    <g className="robot-eye-left">
                        <circle cx="65.6569" cy="81.7274" r="6.57435" fill="#050710"/>
                        <circle cx="67.4498" cy="81.1296" r="2.39067" fill="#01C5A8"/>
                    </g>
                    <g className="robot-eye-right">
                        <circle cx="95.5402" cy="81.7274" r="6.57435" fill="#050710"/>
                        <circle cx="97.3332" cy="81.1296" r="2.39067" fill="#01C5A8"/>
                    </g>

                    {/* ── Mouth ── */}
                    <path
                        className="robot-mouth"
                        d="M71.2572 110.46C74.6661 113.138 83.6754 116.888 92.4412 110.46"
                        stroke="#050710"
                        strokeWidth="1.46097"
                        strokeLinecap="round"
                    />

                    {/* ── Antenna ── */}
                    <g className="robot-antenna">
                        <path d="M70.2832 24.5372C70.1 28.4961 73.5426 29.8067 75.3966 33.303C77.5242 37.3152 78.1461 43.7732 79.7795 43.7732C81.9709 43.7732 83.1398 36.9301 85.6234 32.816C87.4634 29.7678 90.5172 28.8214 90.7367 25.2677C91.0601 20.033 86.4704 16.1643 81.2405 15.7715C75.776 15.3611 70.5365 19.0632 70.2832 24.5372Z" fill="url(#g4)"/>
                    </g>

                </g>
            </svg>
        </>
    );
}